spring.application.name: job-search

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # TODO: 반드시 확인할 것
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server.port: 8080
